AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
# Ignoring rubocop violations on 3rd-party generated files
    - 'db/migrate/20190715213650_add_missing_unique_indices.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20190715213652_add_missing_taggable_index.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20190715213654_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20190715213649_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20190715213653_change_collation_for_tag_names.acts_as_taggable_on_engine.rb'

  TargetRubyVersion: 2.5

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 112  # Maximum line length from `rails new`

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
